In [1]:
import numpy as np

In [2]:
# 1. 生成5阶单位矩阵、8阶均匀分布的随机矩阵、及其下三角矩阵
print("1.")
print("5阶单位矩阵", np.identity(5), sep="\n")
mat1 = np.random.random((8, 8))
print("8阶均匀分布的随机矩阵", mat1, sep="\n")
print("上述矩阵的下三角矩阵", np.array([ [ (mat1[k][l] if k >= l else 0) for l in range(mat1.shape[1]) ] for k in range(mat1.shape[0]) ]), sep="\n")

1.
5阶单位矩阵
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
8阶均匀分布的随机矩阵
[[0.45544056 0.4302889  0.52163508 0.43975211 0.21858903 0.79777994
  0.05970392 0.13124459]
 [0.22062668 0.62131016 0.58264639 0.52190773 0.67120093 0.03858467
  0.76799469 0.25754549]
 [0.80645755 0.94656188 0.13374422 0.69307805 0.30587131 0.59171773
  0.05965034 0.85947656]
 [0.7894116  0.24581141 0.25752065 0.91967816 0.29835124 0.29756872
  0.94038462 0.35972445]
 [0.90521606 0.45665888 0.87703104 0.86520705 0.2859323  0.98966824
  0.95101727 0.44626756]
 [0.96714494 0.38085002 0.32054825 0.74548937 0.72483798 0.03928094
  0.95263321 0.029849  ]
 [0.41407963 0.06659251 0.70112346 0.75930275 0.41499651 0.21546716
  0.86527149 0.1863188 ]
 [0.93077594 0.76579001 0.96105015 0.70411049 0.96419563 0.25440104
  0.19265791 0.9280571 ]]
上述矩阵的下三角矩阵
[[0.45544056 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.22062668 0.62131016 0.         0.         

In [3]:
# 2. 生成列向量 x = [1, 3, ..., 29]^T
x = np.array([ (2 * k + 1) for k in range(15) ]).reshape(15, 1)
print("2. 列向量x:", x, sep="\n")

2. 列向量x:
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]
 [21]
 [23]
 [25]
 [27]
 [29]]


In [4]:
# 3. 生成以x为元素的对角线矩阵A，并输出A的行数
A = np.diag(x.reshape(15))
print("3. 对角线矩阵A (行数: %d):" % A.shape[0], A, sep="\n")

3. 对角线矩阵A (行数: 15):
[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 11  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 13  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 17  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 21  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 23  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 27  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 29]]


In [5]:
# 4. 生成一个与A同阶的正态分布的随机矩阵B
B = np.random.normal(size=A.shape)
print("4. 与A同阶的正态分布的随机矩阵B:", B, sep="\n")

4. 与A同阶的正态分布的随机矩阵B:
[[-4.40863937e-01  6.62307020e-01 -7.15723593e-02  4.24244677e-01
   1.67639751e-01  1.42311406e+00  1.12162273e+00 -1.06489351e+00
   1.85808283e+00 -4.49067945e-01 -1.77643397e-01  7.40128539e-01
  -1.47156649e+00 -1.18071047e+00  1.84435094e-01]
 [-1.05278463e+00 -4.27954870e-01  1.67843621e+00  1.16898104e+00
   5.76769373e-01  1.91232182e-01 -1.85328579e+00  5.89222436e-01
  -3.24104334e-01  6.24926775e-01  1.23078733e-01  1.93182063e-01
  -4.08620335e-02  1.01314957e+00 -4.09993578e-01]
 [ 1.01629783e+00  2.44470889e+00 -6.56188953e-01 -1.31794530e-01
   2.18425673e-01 -1.22801468e+00 -1.56991986e-02 -1.49097341e+00
   1.07616411e+00 -2.04722987e+00 -4.57923114e-02  1.47915572e+00
  -1.88332967e+00 -6.79496599e-04  1.52367474e+00]
 [-2.07009780e+00 -5.86700276e-01  1.89641412e+00  1.63563733e-01
   8.24566955e-02 -1.69765516e-01 -1.83778107e+00 -1.15746266e+00
   1.15145123e+00  8.11610535e-02 -1.43819255e+00  2.16418816e-01
   1.26756923e-01 -2.34262747e-01  

In [6]:
# 5. 输出A与B的Kronecker乘积矩阵C
C = np.kron(A, B)
print("5. A与B的Kronecker乘积矩阵C:", C, sep="\n")

5. A与B的Kronecker乘积矩阵C:
[[-4.40863937e-01  6.62307020e-01 -7.15723593e-02 ... -0.00000000e+00
  -0.00000000e+00  0.00000000e+00]
 [-1.05278463e+00 -4.27954870e-01  1.67843621e+00 ... -0.00000000e+00
   0.00000000e+00 -0.00000000e+00]
 [ 1.01629783e+00  2.44470889e+00 -6.56188953e-01 ... -0.00000000e+00
  -0.00000000e+00  0.00000000e+00]
 ...
 [-0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.79541982e+01
   1.68360869e+01 -6.71768900e+01]
 [-0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.37679129e+01
  -4.66396255e-01  5.47462771e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.98704287e+01
   2.40961020e+01 -6.63224180e+00]]


In [7]:
# 6. 生成A与B点乘得到的矩阵D
D = A * B
print("6. A与B点乘得到的矩阵D:", D, sep="\n")

6. A与B点乘得到的矩阵D:
[[-0.44086394  0.         -0.          0.          0.          0.
   0.         -0.          0.         -0.         -0.          0.
  -0.         -0.          0.        ]
 [-0.         -1.28386461  0.          0.          0.          0.
  -0.          0.         -0.          0.          0.          0.
  -0.          0.         -0.        ]
 [ 0.          0.         -3.28094476 -0.          0.         -0.
  -0.         -0.          0.         -0.         -0.          0.
  -0.         -0.          0.        ]
 [-0.         -0.          0.          1.14494613  0.         -0.
  -0.         -0.          0.          0.         -0.          0.
   0.         -0.          0.        ]
 [-0.          0.         -0.         -0.          8.38394226 -0.
   0.          0.         -0.          0.         -0.          0.
   0.          0.         -0.        ]
 [ 0.          0.          0.          0.          0.         12.82709295
   0.          0.          0.         -0.          0.  

In [8]:
# 7. 生成一个由D的第 8, 4, 10, 13 行与第 7, 1, 6, 9, 2 列组成的子矩阵E
E = D[[7, 3, 9, 12]][ : , [6, 0, 5, 8, 1]]
print("7. 由D的第 8, 4, 10, 13 行与第 7, 1, 6, 9, 2 列组成的子矩阵E:", E, sep="\n")

7. 由D的第 8, 4, 10, 13 行与第 7, 1, 6, 9, 2 列组成的子矩阵E:
[[ 0. -0. -0. -0. -0.]
 [-0. -0. -0.  0. -0.]
 [ 0. -0. -0.  0.  0.]
 [-0. -0. -0. -0.  0.]]


In [9]:
# 8. 求出E的最大元素
print("8. E的最大元素: %s" % E.max())

8. E的最大元素: 0.0
