In [53]:
import numpy as np
import pandas as pd

import scipy
from scipy import optimize

from matplotlib import pyplot as plt
plt.style.use("solarized-light")

In [2]:
champions = pd.read_csv("./champdata.csv")

In [63]:
arr = champions.values[ : , 1 : ]
arr_w1 = (arr[ : , 0 ] - 35) ** (1/3)
arr1 = np.concatenate([[arr_w1.astype("float64")], [arr[ : , 1 ].astype("float64")]], axis=0).T
floss1 = lambda k : np.sum([ (y - k * w1) ** 2 for (w1, y) in list(arr1) ])
minires1 = scipy.optimize.minimize_scalar(floss1)
minires1, minires1.x * arr_w1

(     fun: 1939.3462660901662
     nfev: 10
      nit: 4
  success: True
        x: 106.23197283654902,
 array([314.71180186743504, 337.2654908667902, 357.1492800922133,
        380.63424410582076, 418.1818618264618, 445.99756411966825,
        451.944898580861], dtype=object))

In [64]:
arr = champions.values[ : , 1 : ]
arr_w2 = arr[ : , 0 ] ** (2/3)
arr2 = np.concatenate([[arr_w2.astype("float64")], [arr[ : , 1 ].astype("float64")]], axis=0).T
floss2 = lambda k : np.sum([ (y - k * w2) ** 2 for (w2, y) in list(arr2) ])
minires2 = scipy.optimize.minimize_scalar(floss2)
minires2, minires2.x * arr_w2

(     fun: 1763.622529611162
     nfev: 10
      nit: 4
  success: True
        x: 19.965094256440732,
 array([309.37930169764184, 329.34764826120005, 348.7278280695997,
        373.7616262967596, 418.586791657092, 455.5706078386719,
        463.89181874427027], dtype=object))

In [65]:
arr[ : , 1 ] * (61 / arr[ : , 0 ]) ** (2/3)

array([313.0, 311.8708413613946, 322.9282459083418, 309.5766143286422,
       297.11993249977365, 292.0142288395745, 325.4575595601922],
      dtype=object)

In [66]:
arr[ : , 1 ] * ((42 / (arr[ : , 0 ] - 35)) ** (1/3))

array([367.25663586597176, 363.5000886106948, 376.3482910017395,
       362.82908071192395, 354.97617456521465, 356.01993164347374,
       398.724275033903], dtype=object)